### ISSUE TITLE
Seems to be a problem "Splatting" to xWebSite

### ISSUE THREAD

**Issue by Br4v3St4rr** [dsccommunity/DscWorkshop#113]
Hi,

There seems to be a problem when running 

`(Get-DscSplattedResource -ResourceName xWebSite -ExecutionName $executionName -Properties $item -NoInvoke).Invoke($item)`

When you have nested `AuthenticationInfo` or  `BindingInfo` Present.

**Comment by stehlih** [comment]
Please add an YAML configuration file to reproduce the error.
The nested AuthenticationInfo or BindingInfo Parts are currently not part of the CommonTasks Unit Tests.

**Comment by gaelcolas** [comment]
It's true that the Get-DscSplattedResource does not work with nested type out of the box though.

**Comment by Br4v3St4rr** [comment]
If you see the following:
```
WebSites:
  Items:
    # Remove Default WebSite
    - Name: Default Web Site
      Ensure: Absent
    # Create New WebSite
    - Name: Site Number 1
      ApplicationPool: site1
      Ensure: Present
      PhysicalPath: F:\AFolder\Site1
      PreloadEnabled: true
      AuthenticationInfo:
        Anonymous: True
        Basic: False
        Digest: False
        Windows: False
      BindingInfo:
        - Protocol: http
          Port: 80
          HostName: site1.contoso.com
        - Protocol: https
          Port: 443
          HostName: site1.contos.com
          CertificateThumbprint: 400985E6876BF8D205F383C1B0815FA3F33AD244
          CertificateStoreName: WebHosting
```

AuthenticationInfo and BindingInfo wont work.  I have managed to frig my way around AuthenticationInfo with the DSC Resource Schema.  However getting the Bindings to work dynamically has not been so successful.  I have managed to frig it to meet my current needs though.

@gaelcolas is there a way to modify Get-DscSplattedResource to work with nested type?  It seems to be somewhat difficult?
