### ISSUE TITLE
Issues with Depends on

### ISSUE THREAD

**Issue by Br4v3St4rr** [dsccommunity/DscWorkshop#114]
In the following Example:
```
Disks:
  Disks:
    - DiskId: 2
      DiskIdType: Number
      DriveLetter: F
      PartitionStyle: GPT
      FSFormat: NTFS

FilesAndFolders:
  Items:
    - DestinationPath: F:\ReleaseA\Admin
      Type: Directory
      Ensure: Present
      DependsOn: '[Disk]2'
```

`DependsOn: '[Disk]2'` Throws an error and the resource seems to be malformed?  Perhaps this is just user error?
