### ISSUE TITLE
Datum.InvokeCommand does not work any longer

### ISSUE THREAD

**Issue by nyanhp** [dsccommunity/DscWorkshop#124]
datum.yml
```yaml
DatumHandlers:
  Datum.ProtectedData::ProtectedDatum:
    CommandOptions:
      PlainTextPassword: SomeSecret
  Datum.InvokeCommand::InvokeCommand:
```

Not a single command is resolved, neither in RSOP nor during configuration. There are no error messages, the string is just used verbatim as the configuration parameter.

Input
```yaml
SqlServer:
  DefaultInstanceName: MSSQLSERVER
  Setup:
    Action: Install
    SourcePath: '[x={"\\mediaserver\install\sqlserver\$($Node.SqlVersion)"}]'
```

RSOP
```yaml
SqlServer:
  DefaultInstanceName: MSSQLSERVER
  Setup:
    Action: Install
    SourcePath: '[x={"\\mediaserver\install\sqlserver\$($Node.SqlVersion)"}]'
```
