### ISSUE TITLE
Error when trying to build a DC

### ISSUE THREAD

**Issue by fabricesemti80** [dsccommunity/DscWorkshop#146]
Hi Again.

So I tried to add a DomainController (still testing this in a lab), hoping that - since the role is already there - it is going to be a smooth sailing. But I got a bit of an issue:

I added the file `source\AllNodes\Prod\DSCDC01.yml` :

```yaml
NodeName: '[x={ $Node.Name }=]'
Environment: '[x={ $File.Directory.BaseName } =]'
Role: DomainController
Description: '[x= "$($Node.Role) in $($Node.Environment)" =]'
Location: Frankfurt
Baseline: Server

ComputerSettings:
  Name: '[x={ $Node.NodeName }=]'
  Description: '[x= "$($Node.Role) in $($Node.Environment)" =]'

NetworkIpConfiguration:
  Interfaces:
    - InterfaceAlias: DscWorkshop 0
      IpAddress: 192.168.111.10
      Prefix: 24
      Gateway: 192.168.111.1
      DnsServer:
        - 192.168.111.10
      DisableNetbios: false

PSDscAllowPlainTextPassword: True
PSDscAllowDomainUser: True

LcmConfig:
  ConfigurationRepositoryWeb:
    Server:
      ConfigurationNames: '[x={ $Node.NodeName }=]'

DscTagging:
  Layers:
    - '[x={ Get-DatumSourceFile -Path $File } =]'
```

I understood I only need to change the 
- role
- name of the node
- IP address

Right?

Build script errors out as:

```
DSCDC01 : DSCDC01 : MOF__ NA
    DSCDC01 : DomainController ::> FilesAndFolders .................................................OK
PSDesiredStateConfiguration\node : The term 'AddsDomainController' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:19 char:5
+     node $ConfigurationData.AllNodes.NodeName {
+     ~~~~
    + CategoryInfo          : ObjectNotFound: (AddsDomainController:String) [PSDesiredStateConfiguration\node], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException,PSDesiredStateConfiguration\node

Error occured during compilation of node '' : Compilation errors occurred while processing configuration 'RootConfiguration'. Please review the errors reported in error stream and modify your configuration code appropriately.
Compilation errors occurred while processing configuration 'RootConfiguration'. Please review the errors reported in error stream and modify your
configuration code appropriately.
At C:\windows\system32\windowspowershell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:3917 char:5
+     throw $ErrorRecord
+     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (RootConfiguration:String) [], InvalidOperationException
    + FullyQualifiedErrorId : FailToProcessConfiguration

PSDesiredStateConfiguration\node : The term 'AddsDomainController' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:19 char:5
+     node $ConfigurationData.AllNodes.NodeName {
+     ~~~~
    + CategoryInfo          : ObjectNotFound: (AddsDomainController:String) [PSDesiredStateConfiguration\node], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException,PSDesiredStateConfiguration\node

Exception calling "Invoke" with "1" argument(s): "The term 'AddsDomainController' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."
At line:32 char:13
+             (Get-DscSplattedResource -ResourceName $configurationName ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The config is of course there in the file `source\Roles\DomainController.yml` so not sure why it does not find it?
Am I missing something?

Thanks,
F.

**Comment by fabricesemti80** [comment]
Probably should also add:

it seems to me that the config generated for the DC in `output\RSOP\0.2.0-alpha0650\DSCDC01.yml`:

```yaml
WindowsFeatures:
  Names: -Telnet-Client
Description: DomainController in Prod
DscDiagnostic: {}
Name: DSCDC01
DscLcmController:
  MonitorInterval: 00:15:00
  SendDscTaggingData: true
  AutoCorrectInterval: 00:30:00
  MaintenanceWindowMode: AutoCorrect
  RefreshIntervalOverride: false
  MaintenanceWindowOverride: false
  ControllerInterval: 00:05:00
  RefreshInterval: 00:30:00
  MaxLcmRuntime: 00:30:00
  LogHistoryTimeSpan: 7.00:00:00
  WriteTranscripts: true
  AutoCorrectIntervalOverride: false
PSDscAllowPlainTextPassword: true
PSDscAllowDomainUser: true
ComputerSettings:
  Name: DSCDC01
  Description: DomainController in Prod
  TimeZone: Greenwich Standard Time
  DomainName: prodcontoso.com
  JoinOU: CN=Computers,dc=prodcontoso,dc=com
  Credential: install@contoso:*********
DscLcmMaintenanceWindows:
  MaintenanceWindows:
    Name: Always
    StartTime: 00:00:00
    Timespan: 24:00:00
  DependsOn: '[DscLcmController]DscLcmController'
Configurations:
- FilesAndFolders
- AddsDomainController
- SecurityBase
- WindowsFeatures
- ComputerSettings
- NetworkIpConfiguration
- WindowsEventLogs
- DscLcmController
- DscLcmMaintenanceWindows
- DscTagging
- DscDiagnostic
SecurityBase:
  DependsOn: '[WindowsFeatures]WindowsFeatures'
  Role: Baseline
Baseline: Server
NetworkIpConfiguration:
  Interfaces:
    DnsServer: 192.168.111.10
    Gateway: 192.168.111.1
    DisableNetbios: false
    Prefix: 24
    InterfaceAlias: DscWorkshop 0
    IpAddress: 192.168.111.10
DscTagging:
  Environment: Prod
  Version: 0.3.0
  Layers:
  - AllNodes\Prod\DSCDC01
  - Environment\Prod
  - Locations\Frankfurt
  - Roles\DomainController
  - Baselines\Security
  - Baselines\Server
  - Baselines\DscLcm
Role: DomainController
FilesAndFolders:
  Items:
  - DestinationPath: C:\Test\Prod-Environment
    Type: Directory
  - DestinationPath: C:\Test\Frankfurt
    Type: Directory
NodeName: DSCDC01
Environment: Prod
Location: Frankfurt
LcmConfig:
  ConfigurationRepositoryWeb:
    Server:
      ConfigurationNames: DSCDC01
      RegistrationKey: ec717ee9-b343-49ee-98a2-26e53939eecf
      ServerURL: https://dscpull01.contoso.com:8080/PSDSCPullServer.svc
  ReportServerWeb:
    RegistrationKey: ec717ee9-b343-49ee-98a2-26e53939eecf
    ServerURL: https://dscpull01.contoso.com:8080/PSDSCPullServer.svc
  Settings:
    RefreshFrequencyMins: 30
    AllowModuleOverwrite: true
    ActionAfterReboot: ContinueConfiguration
    RefreshMode: Pull
    RebootNodeIfNeeded: true
    ConfigurationMode: ApplyAndMonitor
    ConfigurationModeFrequencyMins: 30
AddsDomainController:
  SysvolPath: C:\Windows\SYSVOL
  LogPath: C:\Windows\Logs
  IsGlobalCatalog: true
  DatabasePath: C:\Windows\NTDS
  DomainName: contoso.com
  Credential: install@contoso:*********
  SiteName: Default-First-Site-Name
  SafeModeAdministratorPassword: install@contoso:*********
WindowsEventLogs:
  Logs:
  - LogMode: Circular
    IsEnabled: true
    LogName: System
    MaximumSizeInBytes: 20971520
  - LogMode: Circular
    IsEnabled: true
    LogName: Application
    MaximumSizeInBytes: 20971520
  - LogMode: Circular
    IsEnabled: true
    LogName: Security
    MaximumSizeInBytes: 134217728
  DependsOn: '[ComputerSettings]ComputerSettings'
```

So why is the error at build...?
