### ISSUE TITLE
How to apply multiple roles to a node?

### ISSUE THREAD

**Issue by jocassier** [dsccommunity/DscWorkshop#151]
Hello there,

it is possible to apply multiple roles to one node? 
Like: 

```YAML
NodeName: '[x={ $Node.Name }=]'
Environment: '[x={ $File.Directory.BaseName } =]'
Role: 
 - WebServer
 - FileServer
```
If i try so, the "Describing Node Definition Files" test fails with
[-] Role of 'DSCWeb02' is 'WebServer FileServer' and does exist 28ms (26ms|2ms)
   at $node.Role -in $Roles | Should -BeTrue, H:\Code\DscWorkshop\tests\ConfigData\ConfigData.Tests.ps1:176
