### ISSUE TITLE
Override $Datum.Global.

### ISSUE THREAD

**Issue by dan-hughes** [dsccommunity/DscWorkshop#168]
Hi,

Is there a way of overriding the $Datum.Global settings per environment for example?

**Comment by dan-hughes** [comment]
I'm not sure if this is the intended way, but I managed to resolve it by adding the following to my `Environment\Dev.yml`:
```yml
Domain:
  DomainFqdn: dev.contoso.com
  DomainDn: dc=dev,dc=contoso,dc=com
```
Then using `DomainName: '[x={ "$($Datum.Environment.$($Node.Environment).Domain.DomainFqdn)" }=]'` in the `DomainController.yml` role file.

It works, just feels a little dirty.
